language: python

# for container-y googdness:
sudo: false

python:
#  - "3.5"
#  - "3.4"
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: nosetests --with-cov --cov=workfront

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: ZuEv3cCm0DRoVqOujgh18AJlB7BSnaaALKDs4E+tMPdLnM03cYK8J9ge+Phj/fMmRSZMdsvoL/efXaQrDXijYkAhOTkydrelI9tF5KIupfe9OTZ6g+UkP1RdawEgvqW5KmRmLfbvkXm27iCiClaAFkC6/cckNLLGP5ErTEmP6hFEyrO38EiKo8lg/8lE2AbQNsvprlFJgfE0cWoeMnMUoUEXsVHbyVa26IENdSM0X3NfxmaQBl7SX0AEbPrzlly+Jx6juMre9PS5eYOzwgfxjYfO6rJ8YIKjvvykwT94NDkj/yen6pYo73E9tDxwGFIaNCb44LCDEsZsBXI4Kjo1yYdhbRqlXillwJ0lLw49PZ1oHakQSypEKC/V47i1YKOPElZpA3lQMRgIcUckkKJqeZMDUXRPYpk+nVv9yuiRvSQ6O8CyQNmmZa4CXUtCM5QW5VEqJa2CXtBxq2pxKkBcYZVc60lDeyjFAD15ORq8gtJmHAwBgjfsMu2f4ovzWOPTeKfKTMHKmdSp/TXa54Y6OlO2NbKf6FOAiMMfK7rVewPFn0BM4t23USENbTUPD0wJLGCg0BlkRy1mWIKgKRVP7VGEPLqPBE10AKXkM3Wmxz3xDcE6WWMVDPzQW8bQ7wy1bRWf2pcAQMtgCtyxiTkyaDDjdyRPBNWt478n23/v2DI=
  on:
    tags: true
    repo: cjw296/python-workfront
    python: "2.7"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
