language: python

# for container-y googdness:
sudo: false

python:
  - "3.5"
  - "3.4"
  - "2.7"

# command to install dependencies
install: "pip install -Ue .[test,build]"

# command to run tests, e.g. python setup.py test
script: nosetests --with-cov --cov=workfront

after_success:
  - coveralls

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: uAMgPLBlG/GQvUnoob7hHe48mn3UzKM4L6sChHgtkjVrbhiGI+FJxhibrk+XHuET3J64WdJwnEfzg7I6xxIAVDUcLoA1rMvKXWWlHTHbLW2GZXQ6eCQoa/9vHi+EoJAG/zBtw9REv54PqCu8934AKBCvARe50NI90AqW382vJTB8x4SNE8btQDw7VZWxdSWOYzhvZYswbpza9+SVd8mu2f4XFdnVsI+ficQ+L0lkekpkKrnTCK2lSPKBxaFQFAGR2gQza/7YhG4h6p42EyLJHheOgv3uPCHExmFjr2hLtwlZ6uxeuRY0SSENUIOTYvUuMovvx/yJWTbPRqGfe6bqIoVCut2LPn5lvdW6rGAKl59RUZ3MDZwa+mAFii2oxbEVxNr5+/ii1n6rdikVXFrb7eE4EG3hd/r8H7K+eCUv+NsnyuBCTTV68NDsnAxpSq73HpFCiHaEA9RU3VFf/pvp2BUUVxEsTImKPp97xeqYjdqRqIS/y2mrNeUHcGr3C9TTHSYOjRyHkoi4EK7BU8YErd3v61v43dZee+GhTfnIXjoWxYgT7joze/u6CX2zQ4vE7YdsNq06hNq9+o1a+kRAoyXvocDqCCbxgf7uxwCEpHSBlOWfDlYPjowqUfJrzQk1DLN6R6WJYvs7HQQjFnGj7JRpnKd54AAcmcb+3JwxnsY=
  on:
    tags: true
    repo: cjw296/python-workfront
    python: "3.5"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
